version: "3.1"

networks:
  auction-network:
    external: false
    driver: bridge

services:
  postgres:
    image: postgres:bullseye
    container_name: auction-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
    networks:
      - auction-network

  redis:
    image: redis:latest
    container_name: auction-redis
    restart: always
    volumes:
      - ${DATA_DIR}/redis/redis:/usr/local/etc/redis
      - ${DATA_DIR}/redis/data:/data
    networks:
      - auction-network

  celery:
    image: auction-python-image
    container_name: auction-celery
    restart: always
    networks:
      - auction-network
    command: >
      bash -c "celery -A auc worker -l info"

  django:
    image: auction-python-image
    container_name: auction-django
    restart: always
    volumes:
      - ${DATA_DIR}/django/data:/data
    networks:
      - auction-network
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000 --noreload"
