version: "3.1"

networks:
  auction-network:
    external: false
    driver: bridge

services:
  mongodb:
    image: auction-mongo-image
    container_name: auction-mongo
    restart: always
    ports:
      - ${MONGO_CONTAINER_PORT}:27017
    volumes:
      - ${DATA_DIR}/mongo/mongo:/etc/mongo
      - ${DATA_DIR}/mongo/data:/data
    networks:
      - auction-network

  redis:
    image: redis:latest
    container_name: auction-redis
    restart: always
    volumes:
      - ${DATA_DIR}/redis/redis:/usr/local/etc/redis
      - ${DATA_DIR}/redis/data:/data
    networks:
      - auction-network

  celery:
    image: auction-python-image
    container_name: auction-celery
    restart: always
    networks:
      - auction-network
    command: >
      bash -c "celery -A auc worker -l info"

  django:
    image: auction-python-image
    container_name: auction-django
    restart: always
    volumes:
      - ${DATA_DIR}/django/data:/data
    networks:
      - auction-network
    ports:
      - ${DJANGO_CONTAINER_PORT}:8000
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000 --noreload"
