version: "3.1"

networks:
  auction-network:
    external: false
    driver: bridge

volumes:
  auction-mongodb-volume:
    name: auction-mongodb-volume
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_DIR}/mongo

  auction-redis-volume:
    name: auction-redis-volume
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_DIR}/redis/redis

  auction-redis-data-volume:
    name: auction-redis-data-volume
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_DIR}/redis/data

  auction-django-volume:
    name: auction-django-volume
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_DIR}/django

services:
  mongodb:
    image: auction-mongo-image
    container_name: auction-mongodb
    restart: always
    mem_limit: ""
    volumes:
      - auction-mongodb-volume:etc/mongo
    networks:
      - auction-network

  redis:
    image: redis:latest
    container_name: auction-redis
    restart: always
    mem_limit: ""
    volumes:
      - auction-redis-volume:/usr/local/etc/redis
      - auction-redis-data-volume:/data
    networks:
      - auction-network

  celery:
    image: auction-python-image
    container_name: auction-celery
    restart: always
    mem_limit: ""
    networks:
      - auction-network
    command: >
      bash -c "celery -A auc worker -l info"

  django:
    image: auction-python-image
    container_name: auction-django
    restart: always
    mem_limit: ""
    volumes:
      - auction-django-volume:/data
    networks:
      - auction-network
    ports:
      - ${DJANGO_CONTAINER_PORT}:8000
    command: >
      bash -c "; \
      python manage.py runserver 0.0.0.0:8000 --noreload"