version: "3.1"

networks:
  auction-network:
    external: false
    driver: bridge

volumes:
  auction-volume:
    name: auction-volume
    driver: local
    driver_opts:
      o: bind
      device: { YOUR_PATH_TO_FOLDER }

services:
  mongodb:
    build: ./mongo_docker/dockerfile
    image: auctions-mongo-image
    container_name: auction-mongodb
    restart: always
    mem_limit: { YOUR_MEM_LIMIT }
    volumes:
      - auction-volume/mongo:etc/mongo
    networks:
      - auction-network

  redis:
    image: redis:latest
    container_name: auction-redis
    restart: always
    mem_limit: { YOUR_MEM_LIMIT }
    volumes:
      - auction-volume/redis/redis:/usr/local/etc/redis
      - auction-volume/redis/data:/data
    networks:
      - auction-network

  celery:
    build: .
    image: auction-python-image
    container_name: auction-celery
    restart: always
    mem_limit: { YOUR_MEM_LIMIT }
    networks:
      - auction-network
    command: >
      bash -c "celery -A auc worker -l info"

  django:
    image: auction-python-image
    container_name: auction-django
    restart: always
    mem_limit: { YOUR_MEM_LIMIT }
    volumes:
      - auction-volume/django/data:/data
    networks:
      - auction-network
    ports:
      - { YOUR_PORT }:8000
    command: >
      bash -c "; \
      python manage.py runserver 0.0.0.0:8000 --noreload"
    environment:
      - DJANGO_SU_USERNAME="admin"
      - DJANGO_SU_PASSWORD="admin"
      - DJANGO_SU_EMAIL="admin@admin:admin"